
services:
  db_user:
    image: postgres:14-alpine
    container_name: postgres_users
    ports:
      - 5432:5432 # maps container port 5432 to host port 5433 (outside 5433)
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=0880
      - POSTGRES_USER=nexoc
      - POSTGRES_DB=users

  db_content:
    image: postgres:14-alpine
    container_name: postgres_content
    ports:
      - 5433:5432 # maps container port 5432 to host port 5433 (outside 5433)
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data-content
    environment:
      - POSTGRES_PASSWORD=0000
      - POSTGRES_USER=marat
      - POSTGRES_DB=content

  app:
    build: .
    depends_on:
      - db_user
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_user:5432/users
      SPRING_DATASOURCE_USERNAME: nexoc
      SPRING_DATASOURCE_PASSWORD: '0880'
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver

    ports:
      - 8080:8080


volumes:
  db_data_1:
  db_data_2:

