spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

  datasource:
    url: jdbc:postgresql://localhost:5433/users
    username: nexoc
    password: 0880
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: "Here is your actual email address"
    password: "Here is your actual password"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

base:
  url: "http://localhost:8080"




